# Generated by Django 3.0.5 on 2020-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.PositiveIntegerField()),
                ('course', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('ror', 'Ruby on Rails'), ('js', 'JavaScript'), ('npm', 'NodeJs')], max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
